In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5,6])
vector

array([1, 2, 3, 4, 5, 6])

In [3]:
mat = np.array([[1, 2, 3],
              [4, 5, 6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#accessing an cell
print(mat[0][1])
print(mat[0, 1])

2
2


In [5]:
print(vector[3:])
print(vector[:3])

[4 5 6]
[1 2 3]


In [6]:
print(vector.ndim)
print(vector.shape)
print(vector.size)

print(mat.ndim)
print(mat.shape)
print(mat.size)

# len(a.shape) == a.ndim

1
(6,)
6
2
(2, 3)
6
