In [1]:
import numpy as np

In [2]:
print(np.zeros(2))
print(np.ones(2))
print(np.ones(2, dtype=np.int64)) # specify data types
print(np.empty(2)) # random initialization


[0. 0.]
[1. 1.]
[1 1]
[5.e-324 5.e-324]


In [3]:
np.arange(4)

array([0, 1, 2, 3])

In [4]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [5]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])