In [1]:
import numpy as np

mat = np.arange(6).reshape((2, 3))
print(mat)

[[0 1 2]
 [3 4 5]]


In [2]:
print(mat.transpose()) # short for is mat.T
print(mat.T)

[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
